### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kekkokk**
update wrong env key

### CODE REVIEW

**Comment by bholland-bh** [comment]
Good catch!

Thank you!!!

**Review by bholland-bh — APPROVED** [review]

**Comment by hollanbm** [comment]
good catch, thank you!

**Comment by kekkokk** [comment]
made me went crazy yesterday XD
Thank you, worked flawlessly.
also, did you find any documentation about that Tdarr API?

**Comment by hollanbm** [comment]
> made me went crazy yesterday XD
> Thank you, worked flawlessly.
> also, did you find any documentation about that Tdarr API?

Apologies for the headache 😅

Unfortunately, the `scan-files` endpoint I used isn’t published on the tdarr [API docs site](https://tdarr.readme.io/reference/get_status).

**Pull request merged**
